### ISSUE TITLE
LiPodAi certification request for DESIRE

### ISSUE THREAD

**Issue by pelinquin** [3rd-ways-for-EU-exposure-notification/project-DESIRE#3]
Please see the requirements:
https://adox.io/lipodai.pdf
in French...since DESIRE is likely to be French only like the Minitel ;-)

Best regards,

Laurent

**Comment by vincent-grenoble** [comment]
> La gestion de ce dossier révèle tous les attributs d’un pouvoir autoritaire, ne respectant pas les principes de démocratie et de partage des compétences face à un ennemi commun.

(translation: "The management of this file reveals all the attributes of an authoritarian power, which does not respect the principles of democracy and the sharing of powers in the face of a common enemy.")

You got it. And since we are authoritarian (we're in France), we decide to close this thread ;-)

**Comment by pelinquin** [comment]
How do you explain that no source code is publicly shared ?
